spring.application.name=api-gateway
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Route to Activity Service
spring.cloud.gateway.routes[0].id=activity-service
spring.cloud.gateway.routes[0].uri=lb://activity-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/activities/**

# Route to AI Service
spring.cloud.gateway.routes[1].id=ai-service
spring.cloud.gateway.routes[1].uri=lb://ai-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/recommendations/**

spring.cloud.gateway.server.webmvc.routes[0].id=activity-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://activity-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/activities/**

spring.cloud.gateway.server.webmvc.routes[1].id=ai-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ai-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/recommendations/**