spring.application.name=api-gateway
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Apply AuthenticationFilter to all MVC routes
spring.cloud.gateway.server.webmvc.default-filters[0].name=AuthenticationFilter

# Route to Activity Service
spring.cloud.gateway.server.webmvc.routes[0].id=activity-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://activity-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/activities/**

# Route to AI Service
spring.cloud.gateway.server.webmvc.routes[1].id=ai-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ai-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/recommendations/**

# Route to User Service
spring.cloud.gateway.server.webmvc.routes[2].id=user-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://host.docker.internal:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/users/**

# --- Global CORS Configuration ---
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

jwt.secret=${JWT_SECRET}