package com.fitness.userservice.model;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "users") //To give custom name to the table, so there will be
// conflict with the internal user table if there is any inside the DB
@Data // To generate the Getters and Setters
public class User {
    @Id //Marks the field as Primary Key
    @GeneratedValue(strategy = GenerationType.UUID)
    // the line @GeneratedValue(strategy = GenerationType.UUID) is used to tell
    // your application how to automatically create unique primary keys for your database.
    //What this "GenerationType.UUID" does:
    //Meaning: This specific strategy tells the persistence provider (like Hibernate) to
    // generate a Universally Unique Identifier (UUID) compliant with RFC 4122.
    //What it does: It creates a 128-bit value (e.g., 550e8400-e29b-41d4-a716-446655440000)
    // that is globally unique, meaning there is virtually zero chance of a duplicate even across different systems.
    //Key Advantage: Unlike IDENTITY (where the app must wait for the database to assign an ID),
    // UUIDs can be generated by the application before it even talks to the database, making it excellent for distributed systems and microservices.

    //Defining the fields: Which you want to store from a user standpoint like:
    private String id;

    @Column(unique = true, nullable = false)
    private String email;

    @Column(nullable = false)
    private String password;
    private String firstName;
    private String lastName;

    @Enumerated(EnumType.STRING)
    private UserRole role = UserRole.USER;

    @CreationTimestamp //Whenever an Entity instance is inserted into the
    // table or DB, below field will be automatically populated
    private LocalDateTime createdAt;

    @UpdateTimestamp //Whenever an Entity instance is updated in the
    // table or DB, below field will be automatically populated/updated
    private LocalDateTime updatedAt;
}
