# This is Application Properties file
spring.application.name=eureka
server.port=8761

eureka.client.register-with-eureka=false
# We set above to false because, this is a eureka server, and we don't want
# this eureka server to register with itself
eureka.client.fetch-registry=false
# We set above false because this server does not fetch other instances